[package]
name = "reversi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.2.7", features = ["derive"]}
itertools = "0.10.5"
nom = "7.1.3"
rand = "0.8.5"

